kind: pipeline
name: default

platform:
  os: linux
  arch: arm

install:
  image: node:8.6.0

steps:
- name: job0
  image: node
  commands:
  - npm install
  - npm test
  - npm run cov

trigger:
  branch:
  - master
  event:
  - push
